from __future__ import annotations

"""Bundled skill manifest integrity checker for RADIANT-LLM.

MANIFEST.json lives at radiant_llm_skills/MANIFEST.json and is generated by
maintenance_scripts/generate_skill_manifest.py at build/release time. A file whose
SHA-256 matches the manifest hash is developer-signed and loads without a
security scan. A hash mismatch or absence from the manifest means the file
was added or edited after the last release and is scanned like a user skill.
"""

import hashlib
import json
from pathlib import Path
from typing import Dict

MANIFEST_FILENAME = "MANIFEST.json"
MANIFEST_EXTENSIONS = frozenset(
    {".md", ".txt", ".yaml", ".yml", ".py", ".tex", ".i", ".toml", ".cfg"}
)


def _file_hash(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def load_manifest(bundled_root: str | Path) -> Dict[str, str]:
    """Load MANIFEST.json from bundled_root. Returns {} if missing or malformed."""
    manifest_path = Path(bundled_root) / MANIFEST_FILENAME
    try:
        data = json.loads(manifest_path.read_text(encoding="utf-8"))
        if isinstance(data, dict):
            return {str(k): str(v) for k, v in data.items()}
    except Exception:
        pass
    return {}


def verify_bundled_file(
    path: Path,
    manifest: Dict[str, str],
    bundled_root: Path,
) -> str:
    """Return 'verified', 'tampered', or 'unknown' for a single bundled file."""
    try:
        rel = path.resolve().relative_to(bundled_root.resolve()).as_posix()
    except ValueError:
        return "unknown"
    expected = manifest.get(rel)
    if expected is None:
        return "unknown"
    try:
        actual = _file_hash(path)
    except Exception:
        return "unknown"
    return "verified" if actual == expected else "tampered"


def verify_bundled_root(
    bundled_root: Path,
    manifest: Dict[str, str],
) -> Dict[str, str]:
    """Return {rel_path: status} for every file recorded in the manifest."""
    results: Dict[str, str] = {}
    for rel, expected in manifest.items():
        path = bundled_root / rel
        if not path.exists():
            results[rel] = "missing"
            continue
        try:
            actual = _file_hash(path)
            results[rel] = "verified" if actual == expected else "tampered"
        except Exception:
            results[rel] = "unknown"
    return results
